nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:5173']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': null
